CREATE DATABASE IF NOT EXISTS b_friend;
USE b_friend;

CREATE TABLE user_data (
    id int AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);